# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=70),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
